# docker-compose.prod.yml (VERSIÓN FINAL Y VERIFICADA)

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blasting_backend_prod
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: blasting_frontend_prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"

  db:
    image: postgres:16-alpine
    container_name: blasting_db_prod
    restart: unless-stopped
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=blasting_user
      - POSTGRES_PASSWORD=una_contraseña_muy_segura
      - POSTGRES_DB=cloud_blasting_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blasting_user -d cloud_blasting_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
